#!/bin/bash

killall go-filecoin
sleep 3
rm /meta/.filecoin/ -rf
go-filecoin --repodir=/meta/.filecoin init   --genesisfile=/meta/fixtures/genesis.car
nohup go-filecoin --repodir=/meta/.filecoin daemon &

def_node_host='192.168.10.210'
main_node_host=${1:-$def_node_host}
echo $main_node_host
sleep 4
main_ip=`curl -s "ftp://${main_node_host}/main_node_peer_id"`
echo $main_ip
go-filecoin --repodir=/meta/.filecoin swarm connect $main_ip

go-filecoin --repodir=/meta/.filecoin swarm peers
rm -rf /root/gf_data
mkdir /root/gf_data

#获取FIL
main_wallet_addr=`curl -s ftp://${main_node_host}/main_wallet_addr`
local_def_addr=`go-filecoin --repodir=/meta/.filecoin address default`
ssh ${main_node_host} go-filecoin --repodir=/meta/.filecoin message send --from ${main_wallet_addr} --gas-price=0.000000000001 --gas-limit=300 --value 1000 ${local_def_addr}


#查看订单
#go-filecoin --repodir=/meta/.filecoin client list-asks --enc=json
